# Generated by Django 3.2 on 2021-05-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210403_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
