# Generated by Django 3.2 on 2021-06-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='review_headline',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='review_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='review_text',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
