# Generated by Django 3.2 on 2021-06-26 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210622_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='review_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
