# Generated by Django 3.2 on 2021-06-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productreview_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
